/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDoApp;

import java.util.Date;
import controller.ProjectController;
import controller.TaskController;
import java.util.List;
import model.Project;
import model.Task;


public class App {
    
     public static void main(String[] args) throws Exception {
    
    ProjectController projectController = new ProjectController();

    Project project = new Project();
    project.setName("Projeto Teste 2");
    project.setDescription("description");
    project.setCreatedAt(new Date());
    project.setUpdatedAt(new Date());
    projectController.save(project);
//    
//    ProjectController projectController = new ProjectController();
//
//    Project project = new Project();
//    project.setId(1);
//    project.setName("Novo nome do projeto");
//    project.setDescription("description");
//    project.setCreatedAt(new Date());
//    project.setUpdatedAt(new Date());
//    projectController.update(project);

//    ProjectController projectController = new ProjectController();
//
//    List<Project> projects = projectController.getAll();
//    System.out.println("Total de Projetos = " + projects.size());
//    
//    projectController.removeById(1);
//    
//
    TaskController taskController = new TaskController();
//    
    Task task = new Task();
//    task.setIdProject(2);
//    task.setDescription("description");
//    task.setName("Criar Telas da Aplicação");
//    task.setNotes("notes");
//    task.setIsCompleted(false);
//    task.setDeadLine(new Date());
//    task.setUpdatedAt(new Date());
//    task.setCreatedAt(new Date());
//    
//    taskController.save(task);
//    
    task.setName("Alterar telas de Aplicação");
    task.setIdProject(2);
    task.setDescription("hello");
    task.setNotes("notes");
    task.setIsCompleted(false);
    task.setDeadLine(new Date());
    task.setUpdatedAt(new Date());
    task.setCreatedAt(new Date());
    taskController.update(task);
    
    List<Task> tasks = taskController.getAll(2);
    System.out.println("Total de tarefas = " + tasks.size());

}
    
    }
