/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.TaskController;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Project;
import model.Task;

/**
 *
 * @author emman
 */
public class TaskDialogScreen extends javax.swing.JDialog {

        TaskController controller;
        Project project;
        
        public TaskDialogScreen(java.awt.Frame parent, boolean modal) {
                super(parent, modal);
                initComponents();
                hideErrorFields();                
                controller = new TaskController();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanelToolbar = new javax.swing.JPanel();
                jLabelToolbarTitle = new javax.swing.JLabel();
                jLabelToolbarSave = new javax.swing.JLabel();
                jPanelTask = new javax.swing.JPanel();
                jLabelName = new javax.swing.JLabel();
                jTextFieldName = new javax.swing.JTextField();
                jLabelDescription = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTextAreaDescription = new javax.swing.JTextArea();
                jLabelDeadline = new javax.swing.JLabel();
                jLabelNotes = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTextAreaNotes = new javax.swing.JTextArea();
                jFormattedTextFieldDeadline = new javax.swing.JFormattedTextField();
                jLabelNameError = new javax.swing.JLabel();
                jLabelDeadlineError = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setMinimumSize(new java.awt.Dimension(500, 600));

                jPanelToolbar.setBackground(new java.awt.Color(0, 153, 102));

                jLabelToolbarTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabelToolbarTitle.setForeground(new java.awt.Color(255, 255, 255));
                jLabelToolbarTitle.setText("Tarefa");

                jLabelToolbarSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelToolbarSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
                jLabelToolbarSave.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabelToolbarSaveMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout jPanelToolbarLayout = new javax.swing.GroupLayout(jPanelToolbar);
                jPanelToolbar.setLayout(jPanelToolbarLayout);
                jPanelToolbarLayout.setHorizontalGroup(
                        jPanelToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelToolbarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelToolbarTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelToolbarSave, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                jPanelToolbarLayout.setVerticalGroup(
                        jPanelToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelToolbarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelToolbarTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelToolbarSave, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                                .addContainerGap())
                );

                jPanelTask.setBackground(new java.awt.Color(255, 255, 255));

                jLabelName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabelName.setForeground(new java.awt.Color(0, 0, 0));
                jLabelName.setText("Nome:");

                jTextFieldName.setBackground(new java.awt.Color(255, 255, 255));
                jTextFieldName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

                jLabelDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabelDescription.setForeground(new java.awt.Color(0, 0, 0));
                jLabelDescription.setText("Descrição:");

                jTextAreaDescription.setBackground(new java.awt.Color(255, 255, 255));
                jTextAreaDescription.setColumns(20);
                jTextAreaDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jTextAreaDescription.setRows(5);
                jScrollPane1.setViewportView(jTextAreaDescription);

                jLabelDeadline.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabelDeadline.setForeground(new java.awt.Color(0, 0, 0));
                jLabelDeadline.setText("Prazo:");

                jLabelNotes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabelNotes.setForeground(new java.awt.Color(0, 0, 0));
                jLabelNotes.setText("Notas:");

                jTextAreaNotes.setBackground(new java.awt.Color(255, 255, 255));
                jTextAreaNotes.setColumns(20);
                jTextAreaNotes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jTextAreaNotes.setRows(5);
                jScrollPane2.setViewportView(jTextAreaNotes);

                jFormattedTextFieldDeadline.setBackground(new java.awt.Color(255, 255, 255));
                jFormattedTextFieldDeadline.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

                jLabelNameError.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabelNameError.setForeground(new java.awt.Color(255, 0, 0));
                jLabelNameError.setText("Campo de nome é obrigatório");

                jLabelDeadlineError.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabelDeadlineError.setForeground(new java.awt.Color(255, 0, 0));
                jLabelDeadlineError.setText("Campo de prazo é obrigatório");

                javax.swing.GroupLayout jPanelTaskLayout = new javax.swing.GroupLayout(jPanelTask);
                jPanelTask.setLayout(jPanelTaskLayout);
                jPanelTaskLayout.setHorizontalGroup(
                        jPanelTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTaskLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldName)
                                        .addComponent(jLabelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                                        .addComponent(jLabelDeadline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2)
                                        .addComponent(jFormattedTextFieldDeadline)
                                        .addGroup(jPanelTaskLayout.createSequentialGroup()
                                                .addGroup(jPanelTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabelNotes)
                                                        .addComponent(jLabelNameError)
                                                        .addComponent(jLabelDeadlineError))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                jPanelTaskLayout.setVerticalGroup(
                        jPanelTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTaskLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNameError)
                                .addGap(2, 2, 2)
                                .addComponent(jLabelDescription)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabelDeadline)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDeadlineError)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNotes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2)
                                .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jLabelToolbarSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelToolbarSaveMouseClicked
                // TODO add your handling code here:
                
                
                try {
                        if (isFieldsValid()) {
                                
                                Task task = new Task();
                                task.setIdProject(project.getId());
                                task.setName(jTextFieldName.getText());
                                task.setDescription(jTextAreaDescription.getText());
                                task.setNotes(jTextAreaNotes.getText());
                                task.setIsCompleted(false);

                                SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd/MM/yyyy");
                                Date deadline = null;

                                deadline = simpleDateFormat.parse(jFormattedTextFieldDeadline.getText());
                                task.setDeadline(deadline);
                                controller.save(task);

                                JOptionPane.showMessageDialog(rootPane, "Tarefa salva com sucesso!");
                                this.dispose();
                        } else {
                                hideErrorFields();
                                
                                if(jTextFieldName.getText().isEmpty()) {
                                        jLabelNameError.setVisible(true);
                                }
                                
                                if(jFormattedTextFieldDeadline.getText().isEmpty()) {
                                        jLabelDeadlineError.setVisible(true);
                                }
                        }
                        
                }catch(Exception e) {
                        JOptionPane.showMessageDialog(rootPane, e.getMessage());
                }
        }//GEN-LAST:event_jLabelToolbarSaveMouseClicked

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the dialog */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                TaskDialogScreen dialog = new TaskDialogScreen(new javax.swing.JFrame(), true);
                                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                                        @Override
                                        public void windowClosing(java.awt.event.WindowEvent e) {
                                                System.exit(0);
                                        }
                                });
                                dialog.setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JFormattedTextField jFormattedTextFieldDeadline;
        private javax.swing.JLabel jLabelDeadline;
        private javax.swing.JLabel jLabelDeadlineError;
        private javax.swing.JLabel jLabelDescription;
        private javax.swing.JLabel jLabelName;
        private javax.swing.JLabel jLabelNameError;
        private javax.swing.JLabel jLabelNotes;
        private javax.swing.JLabel jLabelToolbarSave;
        private javax.swing.JLabel jLabelToolbarTitle;
        private javax.swing.JPanel jPanelTask;
        private javax.swing.JPanel jPanelToolbar;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTextArea jTextAreaDescription;
        private javax.swing.JTextArea jTextAreaNotes;
        private javax.swing.JTextField jTextFieldName;
        // End of variables declaration//GEN-END:variables

        public void setProject(Project project) {
                this.project = project;
        }
        
        public void hideErrorFields(){
                jLabelDeadlineError.setVisible(false);
                jLabelNameError.setVisible(false);
        }
        
        public boolean isFieldsValid() {
                return (!jTextFieldName.getText().isEmpty()) && (!jFormattedTextFieldDeadline.getText().isEmpty());
        }

}
